### ISSUE TITLE
tapmove doesn't yield clientX property on mobile browsers

### ISSUE THREAD

**Issue by Utkarsh85** [benmajor/jQuery-Touch-Events#102] opened 2016-03-16 05:15 UTC
I am using tapmove for tracing the mouse position. While the clientX property is shown when in a desktop browser like chrome, switching to mobile device emulation built in the chrome browser, the event fired does not contain that property.

**Comment by benmajor** [comment] 2016-03-16 09:17
Can you put together a jsFiddle or similar which demonstrates this behaviour? Thanks.

**Comment by Utkarsh85** [comment] 2016-03-17 03:03
Here is the [jsFiddle](https://jsfiddle.net/66789g4u/) and the screen shots
1. On [desktop](http://i.imgur.com/uaONO4v.png)
2. On [mobile](http://i.imgur.com/I2cwYxW.png)

**Comment by benmajor** [comment] 2016-03-17 10:05
Thanks for putting that together. You appear to be logging the native event (which will be either `touchmove` or `mousemove`, depending on the environment). With `touchmove`, you need to access the `touches` array of the `originalEvent` object within jQuery.

This is not a bug in the library -- `originalEvent.touches[]` will contain the `clientX` and `clientY` values. 

I'll go ahead and close this Issue but, you may wish to read over the documentation about the custom event data returned by the lib:

https://github.com/benmajor/jQuery-Touch-Events#5-callback-data

**Closed by benmajor** 2016-03-17 10:05 UTC
Labels: invalid
